// <auto-generated />
using System;
using Infrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260130103033_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("public")
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Booking.Root.Booking", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateOnly>("BookingDate")
                        .HasColumnType("date")
                        .HasColumnName("booking_date");

                    b.Property<Guid>("BookingId")
                        .HasColumnType("uuid")
                        .HasColumnName("booking_id");

                    b.Property<int>("BookingStatus")
                        .HasColumnType("integer")
                        .HasColumnName("booking_status");

                    b.Property<TimeOnly>("BookingTime")
                        .HasColumnType("time without time zone")
                        .HasColumnName("booking_time");

                    b.Property<string>("CancellationReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("cancellation_reason");

                    b.Property<long>("DevoteeId")
                        .HasColumnType("bigint")
                        .HasColumnName("devotee_id");

                    b.Property<long>("PanditId")
                        .HasColumnType("bigint")
                        .HasColumnName("pandit_id");

                    b.Property<long>("PujaTypeId")
                        .HasColumnType("bigint")
                        .HasColumnName("puja_type_id");

                    b.Property<string>("SpecialInstructions")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("special_instructions");

                    b.HasKey("Id")
                        .HasName("pk_bookings");

                    b.HasIndex("BookingDate")
                        .HasDatabaseName("ix_bookings_booking_date");

                    b.HasIndex("BookingId")
                        .IsUnique()
                        .HasDatabaseName("ix_bookings_booking_id");

                    b.HasIndex("DevoteeId")
                        .HasDatabaseName("ix_bookings_devotee_id");

                    b.HasIndex("PanditId")
                        .HasDatabaseName("ix_bookings_pandit_id");

                    b.ToTable("bookings", "public");
                });

            modelBuilder.Entity("Domain.Common.ValueObjects.PanditVerification", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("CreatedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date");

                    b.Property<string>("DocumentName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("document_name");

                    b.Property<string>("DocumentPath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("document_path");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("boolean")
                        .HasColumnName("is_verified");

                    b.Property<long>("LastModifiedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("last_modified_by");

                    b.Property<DateTimeOffset?>("LastModifiedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_modified_date");

                    b.Property<long?>("PanditId")
                        .HasColumnType("bigint")
                        .HasColumnName("pandit_id");

                    b.Property<Guid>("VerificationId")
                        .HasColumnType("uuid")
                        .HasColumnName("verification_id");

                    b.HasKey("Id")
                        .HasName("pk_pandit_verifications");

                    b.HasIndex("PanditId")
                        .HasDatabaseName("ix_pandit_verifications_pandit_id");

                    b.HasIndex("VerificationId")
                        .IsUnique()
                        .HasDatabaseName("ix_pandit_verifications_verification_id");

                    b.ToTable("pandit_verifications", "public");
                });

            modelBuilder.Entity("Domain.Devotee.Entities.DevoteeVerification", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("CreatedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date");

                    b.Property<long?>("DevoteeId")
                        .HasColumnType("bigint")
                        .HasColumnName("devotee_id");

                    b.Property<string>("DocumentName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("document_name");

                    b.Property<string>("DocumentPath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("document_path");

                    b.Property<bool>("IsVerified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_verified");

                    b.Property<long>("LastModifiedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("last_modified_by");

                    b.Property<DateTimeOffset?>("LastModifiedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_modified_date");

                    b.Property<Guid>("VerificationId")
                        .HasColumnType("uuid")
                        .HasColumnName("verification_id");

                    b.HasKey("Id")
                        .HasName("pk_devotee_verifications");

                    b.HasIndex("DevoteeId")
                        .HasDatabaseName("ix_devotee_verifications_devotee_id");

                    b.HasIndex("VerificationId")
                        .IsUnique()
                        .HasDatabaseName("ix_devotee_verifications_verification_id");

                    b.ToTable("devotee_verifications", "public");
                });

            modelBuilder.Entity("Domain.Devotee.Root.Devotee", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("CreatedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date");

                    b.Property<Guid>("DevoteeId")
                        .HasColumnType("uuid")
                        .HasColumnName("devotee_id");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("full_name");

                    b.Property<long>("LastModifiedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("last_modified_by");

                    b.Property<DateTimeOffset?>("LastModifiedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_modified_date");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.Property<int>("VerificationState")
                        .HasColumnType("integer")
                        .HasColumnName("verification_state");

                    b.HasKey("Id")
                        .HasName("pk_devotees");

                    b.HasIndex("DevoteeId")
                        .IsUnique()
                        .HasDatabaseName("ix_devotees_devotee_id");

                    b.ToTable("devotees", "public");
                });

            modelBuilder.Entity("Domain.Navigation.Root.NavigationItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Icon")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("icon");

                    b.Property<long?>("ParentId")
                        .HasColumnType("bigint")
                        .HasColumnName("parent_id");

                    b.Property<string>("RequiredPermission")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("required_permission");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("title");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("url");

                    b.HasKey("Id")
                        .HasName("pk_navigation_items");

                    b.HasIndex("ParentId")
                        .HasDatabaseName("ix_navigation_items_parent_id");

                    b.ToTable("navigation_items", "public");
                });

            modelBuilder.Entity("Domain.Pandit.Entities.PujaType", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("CreatedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsRecurring")
                        .HasColumnType("boolean")
                        .HasColumnName("is_recurring");

                    b.Property<long>("LastModifiedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("last_modified_by");

                    b.Property<DateTimeOffset?>("LastModifiedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_modified_date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<long?>("PanditId")
                        .HasColumnType("bigint")
                        .HasColumnName("pandit_id");

                    b.Property<Guid>("PujaTypeId")
                        .HasColumnType("uuid")
                        .HasColumnName("puja_type_id");

                    b.HasKey("Id")
                        .HasName("pk_puja_types");

                    b.HasIndex("PanditId")
                        .HasDatabaseName("ix_puja_types_pandit_id");

                    b.HasIndex("PujaTypeId")
                        .IsUnique()
                        .HasDatabaseName("ix_puja_types_puja_type_id");

                    b.ToTable("puja_types", "public");
                });

            modelBuilder.Entity("Domain.Pandit.Entities.Review", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Comment")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("comment");

                    b.Property<long>("CreatedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date");

                    b.Property<long>("LastModifiedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("last_modified_by");

                    b.Property<DateTimeOffset?>("LastModifiedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_modified_date");

                    b.Property<long?>("PanditId")
                        .HasColumnType("bigint")
                        .HasColumnName("pandit_id");

                    b.Property<int>("Rating")
                        .HasColumnType("integer")
                        .HasColumnName("rating");

                    b.Property<Guid>("ReviewId")
                        .HasColumnType("uuid")
                        .HasColumnName("review_id");

                    b.HasKey("Id")
                        .HasName("pk_reviews");

                    b.HasIndex("PanditId")
                        .HasDatabaseName("ix_reviews_pandit_id");

                    b.HasIndex("ReviewId")
                        .IsUnique()
                        .HasDatabaseName("ix_reviews_review_id");

                    b.ToTable("reviews", "public");
                });

            modelBuilder.Entity("Domain.Pandit.Root.Pandit", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<decimal?>("AverageRating")
                        .HasColumnType("numeric")
                        .HasColumnName("average_rating");

                    b.Property<long>("CreatedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date");

                    b.Property<int>("ExperienceInYears")
                        .HasColumnType("integer")
                        .HasColumnName("experience_in_years");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("full_name");

                    b.Property<string>("Languages")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("languages");

                    b.Property<long>("LastModifiedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("last_modified_by");

                    b.Property<DateTimeOffset?>("LastModifiedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_modified_date");

                    b.Property<Guid>("PanditId")
                        .HasColumnType("uuid")
                        .HasColumnName("pandit_id");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.Property<int>("VerificationState")
                        .HasColumnType("integer")
                        .HasColumnName("verification_state");

                    b.HasKey("Id")
                        .HasName("pk_pandits");

                    b.HasIndex("PanditId")
                        .IsUnique()
                        .HasDatabaseName("ix_pandits_pandit_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_pandits_user_id");

                    b.ToTable("pandits", "public");
                });

            modelBuilder.Entity("Domain.Booking.Root.Booking", b =>
                {
                    b.OwnsOne("Domain.ValueObjects.Address", "PujaVenue", b1 =>
                        {
                            b1.Property<long>("BookingId")
                                .HasColumnType("bigint")
                                .HasColumnName("id");

                            b1.Property<string>("AddressLine1")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("puja_venue_address_line1");

                            b1.Property<string>("AddressLine2")
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("puja_venue_address_line2");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("puja_venue_city");

                            b1.Property<string>("Country")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("puja_venue_country");

                            b1.Property<string>("PostalCode")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("puja_venue_postal_code");

                            b1.Property<string>("State")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("puja_venue_state");

                            b1.Property<string>("Street")
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("puja_venue_street");

                            b1.Property<string>("Timezone")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("puja_venue_timezone");

                            b1.HasKey("BookingId");

                            b1.ToTable("bookings", "public");

                            b1.WithOwner()
                                .HasForeignKey("BookingId")
                                .HasConstraintName("fk_bookings_bookings_id");
                        });

                    b.Navigation("PujaVenue")
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Common.ValueObjects.PanditVerification", b =>
                {
                    b.HasOne("Domain.Pandit.Root.Pandit", null)
                        .WithMany("Verifications")
                        .HasForeignKey("PanditId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_pandit_verifications_pandits_pandit_id");
                });

            modelBuilder.Entity("Domain.Devotee.Entities.DevoteeVerification", b =>
                {
                    b.HasOne("Domain.Devotee.Root.Devotee", null)
                        .WithMany("Verifications")
                        .HasForeignKey("DevoteeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_devotee_verifications_devotees_devotee_id");
                });

            modelBuilder.Entity("Domain.Devotee.Root.Devotee", b =>
                {
                    b.OwnsOne("Domain.ValueObjects.Address", "Address", b1 =>
                        {
                            b1.Property<long>("DevoteeId")
                                .HasColumnType("bigint")
                                .HasColumnName("id");

                            b1.Property<string>("AddressLine1")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("address_address_line1");

                            b1.Property<string>("AddressLine2")
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("address_address_line2");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("address_city");

                            b1.Property<string>("Country")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("address_country");

                            b1.Property<string>("PostalCode")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("address_postal_code");

                            b1.Property<string>("State")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("address_state");

                            b1.Property<string>("Street")
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("address_street");

                            b1.Property<string>("Timezone")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("address_timezone");

                            b1.HasKey("DevoteeId");

                            b1.ToTable("devotees", "public");

                            b1.WithOwner()
                                .HasForeignKey("DevoteeId")
                                .HasConstraintName("fk_devotees_devotees_id");
                        });

                    b.Navigation("Address")
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Navigation.Root.NavigationItem", b =>
                {
                    b.HasOne("Domain.Navigation.Root.NavigationItem", null)
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_navigation_items_navigation_items_parent_id");
                });

            modelBuilder.Entity("Domain.Pandit.Entities.PujaType", b =>
                {
                    b.HasOne("Domain.Pandit.Root.Pandit", null)
                        .WithMany("PujaTypes")
                        .HasForeignKey("PanditId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_puja_types_pandits_pandit_id");
                });

            modelBuilder.Entity("Domain.Pandit.Entities.Review", b =>
                {
                    b.HasOne("Domain.Pandit.Root.Pandit", null)
                        .WithMany("Reviews")
                        .HasForeignKey("PanditId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_reviews_pandits_pandit_id");
                });

            modelBuilder.Entity("Domain.Pandit.Root.Pandit", b =>
                {
                    b.OwnsOne("Domain.ValueObjects.Address", "Address", b1 =>
                        {
                            b1.Property<long>("PanditId")
                                .HasColumnType("bigint")
                                .HasColumnName("id");

                            b1.Property<string>("AddressLine1")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("address_address_line1");

                            b1.Property<string>("AddressLine2")
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("address_address_line2");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("address_city");

                            b1.Property<string>("Country")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("address_country");

                            b1.Property<string>("PostalCode")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("address_postal_code");

                            b1.Property<string>("State")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("address_state");

                            b1.Property<string>("Street")
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("address_street");

                            b1.Property<string>("Timezone")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("address_timezone");

                            b1.HasKey("PanditId");

                            b1.ToTable("pandits", "public");

                            b1.WithOwner()
                                .HasForeignKey("PanditId")
                                .HasConstraintName("fk_pandits_pandits_id");
                        });

                    b.Navigation("Address")
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Devotee.Root.Devotee", b =>
                {
                    b.Navigation("Verifications");
                });

            modelBuilder.Entity("Domain.Navigation.Root.NavigationItem", b =>
                {
                    b.Navigation("Children");
                });

            modelBuilder.Entity("Domain.Pandit.Root.Pandit", b =>
                {
                    b.Navigation("PujaTypes");

                    b.Navigation("Reviews");

                    b.Navigation("Verifications");
                });
#pragma warning restore 612, 618
        }
    }
}
